name: judge_system

services:
  web:
    image: ghcr.io/ayushbhagat151105/judge_system-web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: judge_system-web
    ports:
      - "3003:3000"
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  server:
    image: ghcr.io/ayushbhagat151105/judge_system-server:latest
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    container_name: judge_system-server
    ports:
      - "3004:3000"
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
