name: judge_system

services:
  postgres:
    image: postgres
    container_name: judge_system-postgres
    environment:
      POSTGRES_DB: judge_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - judge_system_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  judge_system_postgres_data:
